# how to run
python3 pgdiffsim-gt.py offscreen

# had to manually install pycallgraph module, using pip3 (wouldn't work with python3 otherwise)
# installs in $USER/.local !
# later uninstalled, because didn't work
pip3 install pycallgraph

# simple timing of total execution speed
time python3 pgdiffsim.py offscreen
